### ISSUE TITLE
Dead links - Oslo syllabus

### ISSUE THREAD

**Issue by Jamie-L-Cross** [econ-ark/TITLARK#3]
Links for selected readings in Section 3 are dead. Suggested links:
Reiter (2009) - link: https://www.sciencedirect.com/science/article/pii/S0165188908001528
Boppart, Krusell, and Mitman (2018) - link: https://www.sciencedirect.com/science/article/pii/S0165188918300022
Auclert (2019) - link: https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.20160137

**Comment by llorracc** [comment]
Thanks for pointing this out.  They _do_ work in [the html version](https://econ-ark.github.io/TITLARK/Courses/HA-Macro/2020-01-Oslo/syllabus/syllabus-Oslo.html) and the [PDF Version](https://github.com/econ-ark/TITLARK/blob/master/Courses/HA-Macro/2020-01-Oslo/syllabus/Syllabus-Oslo.pdf), but you are right that the document-internal links do not work in the markdown document.  It turns out that this is [a problem](https://tex.stackexchange.com/questions/264227/pandoc-breaks-hyperlinks-in-latex-file-conversion) with `pandoc` which is the tool I use to convert from LaTeX (which is kind of my native language) into markdown and HTML.  

I've added a warning at the top of the Syllabus-Oslo.md file with a link to the html version, which is better in a few other ways as well.
